# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_transfer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66ile_transfer.proto\x12\x13\x66ileTransferPackage\"O\n\x13\x46ileTransferRequest\x12\x10\n\x08\x66ileName\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ileSize\x18\x02 \x01(\x0c\x12\x14\n\x0c\x66ileContents\x18\x03 \x01(\x0c\"\'\n\x14\x46ileTransferResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2v\n\x13\x46ileTransferService\x12_\n\x08SendFile\x12(.fileTransferPackage.FileTransferRequest\x1a).fileTransferPackage.FileTransferResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_transfer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILETRANSFERREQUEST._serialized_start=44
  _FILETRANSFERREQUEST._serialized_end=123
  _FILETRANSFERRESPONSE._serialized_start=125
  _FILETRANSFERRESPONSE._serialized_end=164
  _FILETRANSFERSERVICE._serialized_start=166
  _FILETRANSFERSERVICE._serialized_end=284
# @@protoc_insertion_point(module_scope)
